apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: com.company.domain.subdomain.boundedcontext.aggregate.events
spec:
  partitions: 16
  replicas: 3
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
    min.insync.replicas: 2